version: '3'
services:
  app1:
    build:
      context: ./adservice
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/adservice:latest
    
  app2:
    build:
      context: ./cartservice
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/cartservice:latest
    
  app3:
    build:
      context: ./checkoutservice
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/checkoutservice:latest
    
  app4:
    build:
      context: ./currencyservice
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/currencyservice:latest
    
  app5:
    build:
      context: ./emailservice
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/emailservice:latest
  
  app6:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
  
  app7: 
    build:
      context: ./loadgenerator
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/loadgenerator:latest
  
  app8:  
    build:
      context: ./paymentservice
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/paymentservice:latest

  app9:  
    build:
      context: ./productcatalogservice
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/productcatalogservice:latest
  
  app10:
    build:
      context: ./recommendationservice
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/recommendationservice:latest
  
  app11:    
    build:
      context: ./shippingservice
      dockerfile: Dockerfile
    image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/shippingservice:latest
  
  # Uncomment and modify the following block if needed
  # app12:
  #   build:
  #     context: ./shoppingassistantservice
  #     dockerfile: Dockerfile
  #   image: 654654355718.dkr.ecr.ap-south-1.amazonaws.com/shoppingassistantservice:latest

# To build the images
# Run: docker-compose build
